sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - "$HOME/virtualenv/python2.7.9"
env:
  global:
    - SENTRY_LIGHT_BUILD=1
    - SKIP_BACKEND_VALIDATION=1
install:
  - pip install -e .
  - pip install "file://`pwd`#egg=sentry-auth-github[tests]"
script:
  - py.test
after_success:
  - codecov
